# Workflow
name: validate-mobile

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Workflow Jobs
jobs:
  # job called "ci"
  ci:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Sets up node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Expo CLI
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          expo-cache: true
      - run: git submodule update --init --recursive
      - run: yarn install
      - run: yarn build
      - run: yarn prettier
      - run: yarn lint
      - run: yarn precheck
      # upload coverage to codecov
      - uses: codecov/codecov-action@v3
