# Workflow
name: Living Snow Project; Continuous Integration

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Workflow Jobs
jobs:
  # job called "ci"
  ci:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Expo CLI
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-cache: true
      - run: git submodule update --init --recursive
      - run: yarn install
      - run: yarn pretty
      - run: yarn lint
      - run: yarn run tsc
      - run: yarn test